DictionaryMVCWebApp/Models/ErrorViewModel.cs
using System;

namespace DictionaryMVCWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DictionaryMVCWebApp/Models/Word.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DictionaryMVCWebApp.Models
{
    public class Word
    {
        public int Id { get; set; }
        public string Words { get; set; }
        public string Definition { get; set; }

        public Word()
        {

        }
    }
}

DictionaryMVCWebApp/Controllers/HomeController.cs
using DictionaryMVCWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DictionaryMVCWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Index1() {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DictionaryMVCWebApp/Controllers/WordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DictionaryMVCWebApp.Data;
using DictionaryMVCWebApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace DictionaryMVCWebApp.Controllers
{
    public class WordsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WordsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Words
        public async Task<IActionResult> Index()
        {
            return View(await _context.Word.ToListAsync());
        }

        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        public async Task<IActionResult> ShowSearchResults(string SearchWord)
        {

            return View("Index", await _context.Word.Where(j => j.Words.StartsWith(SearchWord)).ToListAsync());
        }


        // GET: Words/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var word = await _context.Word
                .FirstOrDefaultAsync(m => m.Id == id);
            if (word == null)
            {
                return NotFound();
            }

            return View(word);
        }

        // GET: Words/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Words/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Words,Definition")] Word word)
        {
            if (ModelState.IsValid)
            {
                _context.Add(word);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(word);
        }

        // GET: Words/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var word = await _context.Word.FindAsync(id);
            if (word == null)
            {
                return NotFound();
            }
            return View(word);
        }

        // POST: Words/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Words,Definition")] Word word)
        {
            if (id != word.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(word);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WordExists(word.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(word);
        }

        // GET: Words/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var word = await _context.Word
                .FirstOrDefaultAsync(m => m.Id == id);
            if (word == null)
            {
                return NotFound();
            }

            return View(word);
        }

        // POST: Words/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var word = await _context.Word.FindAsync(id);
            _context.Word.Remove(word);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WordExists(int id)
        {
            return _context.Word.Any(e => e.Id == id);
        }
    }
}

DictionaryMVCWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To Dictionary</h1>
    @*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXqwzBLGNWCcmXFQLufc37Kt0JecjYk0JzvRWydk6s&s" />
</div>


<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100 h-50" src="https://www.collinsdictionary.com/images/full/dictionary_168552845.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100 h-50" src="https://img.freepik.com/premium-photo/dictionary-study-translate-bilingual-english-background-book_488220-5456.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100 h-25" src="https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_center,w_730,h_487/k%2Farchive%2F03bccd4dd859db2ca60ad9a1864954aead556e7a" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

DictionaryMVCWebApp/Views/Home/Index1.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

{
    <h1>h3llo</h1>
}

DictionaryMVCWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DictionaryMVCWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" >
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DictionaryMVCWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Words" asp-action="ShowSearchForm">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Words" asp-action="Index">Words</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Words" asp-action="Create">Add➕</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top fixed-bottom footer text-muted mb-3">
        <div class="container">
            &copy; 2022 - DictionaryMVCWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
            </svg>
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
            </svg>

            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
            </svg>

        </div>
       
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

DictionaryMVCWebApp/Views/Words/Create.cshtml
@model DictionaryMVCWebApp.Models.Word

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Word</h4>
<hr />
<div class="row card">
    <div class="col-md-4 row card text-white bg-info mb-3">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Words" class="control-label"></label>
                <input asp-for="Words" class="form-control" />
                <span asp-validation-for="Words" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Definition" class="control-label"></label>
                <input asp-for="Definition" class="form-control" />
                <span asp-validation-for="Definition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DictionaryMVCWebApp/Views/Words/Delete.cshtml
@model DictionaryMVCWebApp.Models.Word

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>

    <div>
        <h4>Word</h4>
        <hr />

        <h4 class="card-title"> @Html.DisplayNameFor(model => model.Words)</h4>
        <div class="card text-white bg-info mb-3" style="max-width: 25rem;">
            <div class="card-body">
                <h7 class="card-text"> @Html.DisplayNameFor(model => model.Words) </h7>
                <h5 class="card-text"> @Html.DisplayFor(model => model.Words) </h5>
                <h7 class="card-text"> @Html.DisplayNameFor(model => model.Definition) </h7>
                <h5 class="card-text"> @Html.DisplayFor(model => model.Definition) </h5>

                <div class="card-footer">
                    <a asp-action="Index" class="btn btn-light">Back to List</a>
                </div>
            </div>
        </div>
  
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
    </form>
</div>

DictionaryMVCWebApp/Views/Words/Details.cshtml
@model DictionaryMVCWebApp.Models.Word

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Word</h4>
    <hr />
 
    <h4 class="card-title"> @Html.DisplayNameFor(model => model.Words)</h4>
    <div class="card text-white bg-info mb-3" style="max-width: 25rem;">
        <div class="card-body">
            <h7 class="card-text"> @Html.DisplayNameFor(model => model.Words) </h7>
            <h5 class="card-text"> @Html.DisplayFor(model => model.Words) </h5>
            <h7 class="card-text"> @Html.DisplayNameFor(model => model.Definition) </h7>
            <h5 class="card-text"> @Html.DisplayFor(model => model.Definition) </h5>

            <div class="card-footer">
                <a asp-action="Index" class="btn btn-light">Back to List</a>
            </div>
        </div>
    </div>
</div>

DictionaryMVCWebApp/Views/Words/Edit.cshtml
@model DictionaryMVCWebApp.Models.Word

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<hr />
<div class="card">
    <div class="col-md-4 row card text-white bg-info mb-3" style="max-width: 25rem;">
        <form asp-action="Edit" class="card-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Words" class="control-label"></label>
                <input asp-for="Words" class="form-control" />
                <span asp-validation-for="Words" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Definition" class="control-label"></label>
                <input asp-for="Definition" class="form-control" />
                <span asp-validation-for="Definition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="Index" class="card-footer btn btn-light m-3">Back to List</a>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DictionaryMVCWebApp/Views/Words/Index.cshtml
@model IEnumerable<DictionaryMVCWebApp.Models.Word>

@{
    ViewData["Title"] = "Index";
}



@*<p>
        <a asp-action="Create">Create New</a>
    </p>*@

<h4 class="card-title mt-5"> @Html.DisplayNameFor(model => model.Words)</h4>

@foreach (var item in Model)
{
    
    <div class="card text-white bg-info mb-3" style="max-width: 25rem;">
        <div class="card-body">
            <h5 class="card-text">  @Html.DisplayFor(modelItem => item.Words)</h5>

            <a asp-action="Edit" asp-route-id="@item.Id" class="card-link btn btn-outline-light">Edit✏️</a>
            <a asp-action="Details" asp-route-id="@item.Id" class="card-link btn btn-outline-light">Details🗒️</a>
            <a asp-action="Delete" asp-route-id="@item.Id" class="card-link btn btn-outline-light">Delete🗑️</a>


        </div>
    </div>
}

DictionaryMVCWebApp/Views/Words/ShowSearchForm.cshtml
<h4>Search For word</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            
            <div class="form-group">
                <label for="SearchWord" class="control-label"></label>
                <input name="SearchWord" class="form-control" />
                
            </div>
            
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}